
spring:
  outout:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost/tweets
    username: root
    password:
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update